
version: "3.9"
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8083:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - node

  php:
    build: ./docker/php
    container_name: ec-php
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      PHP_MEMORY_LIMIT: 512M
    depends_on:
      - mysql

  node:
    build: ./docker/node
    container_name: ec-node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  mysql:
    image: mysql:8.0
    container_name: ec-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ec_shop
      MYSQL_USER: ec_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ecdb:/var/lib/mysql

volumes:
  ecdb:
